import { render, screen } from '@testing-library/react';
import React from 'react';
import { describe, expect, it } from 'vitest';

import { MessageBox } from '../message-box';

describe('MessageBox skeleton width', () => {
    // A runtime-built `w-[300px]` class is never generated by Tailwind, so lengths must be inline.
    it.each([
        [300, '300px'],
        ['240px', '240px'],
        ['50%', '50%'],
    ])('applies %p as an inline width', (width, expected) => {
        render(<MessageBox isLoading loadingType="skeleton" width={width} />);
        const box = screen.getByRole('status');
        expect(box.style.width).toBe(expected);
        expect(box.className).not.toMatch(/w-\[/);
    });

    it('treats a non-length string as a Tailwind class', () => {
        render(<MessageBox isLoading loadingType="skeleton" width="w-96" />);
        const box = screen.getByRole('status');
        expect(box.className).toContain('w-96');
        expect(box.style.width).toBe('');
    });
});
