import { execSync } from 'child_process';
import fs from 'fs/promises';
import path from 'path';
import type { DiscoveredModel } from './ModelDiscovery';
import { Logger } from '../utils/logger';

export interface GenerateMigrationOptions {
  models: DiscoveredModel[];
  name: string;
  feature?: string;
  outputDir: string;
}

export class DrizzleGenerator {
  /**
   * Generate a migration from discovered models
   */
  async generateMigration(options: GenerateMigrationOptions): Promise<string> {
    const { models, name, outputDir } = options;
    const timestamp = Date.now();
    const migrationName = `${timestamp}_${name}`;

    Logger.info(`Generating migration: ${migrationName}`);

    // 1. Create temporary directory for drizzle-kit
    const tempDir = path.join(outputDir, '.temp-' + timestamp);
    await fs.mkdir(tempDir, { recursive: true });

    try {
      // 2. Generate schema file
      const schemaFile = path.join(tempDir, 'schema.ts');
      const schemaContent = this.generateSchemaFile(models);
      await fs.writeFile(schemaFile, schemaContent);

      // 3. Create drizzle.config.ts
      const configFile = path.join(tempDir, 'drizzle.config.ts');
      await fs.writeFile(
        configFile,
        `import { defineConfig } from 'drizzle-kit';

export default defineConfig({
  schema: './schema.ts',
  out: './migrations',
  dialect: 'sqlite',
  driver: 'd1-http',
});
`
      );

      // 4. Run drizzle-kit generate
      Logger.info('Running drizzle-kit generate...');
      try {
        execSync('npx drizzle-kit generate', {
          cwd: tempDir,
          stdio: 'pipe',
          encoding: 'utf-8',
        });
      } catch (error: any) {
        Logger.error('Drizzle-kit generation failed');
        Logger.error(error.stderr || error.message);
        throw new Error('Failed to generate migration with drizzle-kit');
      }

      // 5. Read generated SQL
      const migrationsDir = path.join(tempDir, 'migrations');
      const sqlFiles = await fs.readdir(migrationsDir);

      // Find the SQL file (drizzle-kit generates with timestamp)
      const sqlFile = sqlFiles.find((f) => f.endsWith('.sql'));
      if (!sqlFile) {
        throw new Error('No SQL file generated by drizzle-kit');
      }

      const sqlPath = path.join(migrationsDir, sqlFile);
      const sqlContent = await fs.readFile(sqlPath, 'utf-8');

      // 6. Generate TypeScript migration file
      const migrationContent = this.wrapInMigration(migrationName, sqlContent, options.feature);

      // Ensure output directory exists
      await fs.mkdir(outputDir, { recursive: true });

      const migrationPath = path.join(outputDir, `${migrationName}.ts`);
      await fs.writeFile(migrationPath, migrationContent);

      Logger.success(`Migration created: ${migrationPath}`);

      return migrationPath;
    } finally {
      // 7. Cleanup temp files
      try {
        await fs.rm(tempDir, { recursive: true, force: true });
      } catch (error) {
        // Ignore cleanup errors
      }
    }
  }

  /**
   * Generate a schema file from discovered models
   */
  private generateSchemaFile(models: DiscoveredModel[]): string {
    const imports = new Set<string>();
    const tableExports: string[] = [];

    // Collect all unique sources and generate imports
    const sourceModels = new Map<string, string[]>();

    for (const model of models) {
      if (!sourceModels.has(model.source)) {
        sourceModels.set(model.source, []);
      }
      sourceModels.get(model.source)!.push(model.name);
    }

    // Generate import statements
    let content = '// Auto-generated schema for migration\n';
    content += '// This file is temporary and will be deleted after migration generation\n\n';

    for (const [source, modelNames] of sourceModels.entries()) {
      // Import the table schemas
      const tableNames = modelNames.map((name) => {
        // Try to import both the model and the table
        const model = models.find((m) => m.name === name);
        return `${model!.tableName}Table`;
      });

      if (source.startsWith('.')) {
        // Local import
        content += `import { ${tableNames.join(', ')} } from '${source}';\n`;
      } else {
        // Package import
        content += `import { ${tableNames.join(', ')} } from '${source}';\n`;
      }
    }

    content += '\n';

    // Export all tables
    for (const model of models) {
      content += `export { ${model.tableName}Table };\n`;
    }

    return content;
  }

  /**
   * Wrap SQL in a TypeScript migration file
   */
  private wrapInMigration(name: string, sql: string, feature?: string): string {
    // Parse SQL to extract table names for down migration
    const tableNames = this.extractTableNames(sql);
    const downMigration = this.generateDownMigration(tableNames);

    return `// Migration: ${name}
// Feature: ${feature || 'app'}
// Generated: ${new Date().toISOString()}

export interface MigrationDatabase {
  run(sql: string): Promise<void>;
  exec(sql: string): Promise<void>;
  all(sql: string, params?: any[]): Promise<any[]>;
}

export default {
  name: "${name}",
  feature: "${feature || 'app'}",

  async up(db: MigrationDatabase): Promise<void> {
    await db.exec(\`${sql.replace(/`/g, '\\`').trim()}\`);
  },

  async down(db: MigrationDatabase): Promise<void> {
    ${downMigration}
  }
};
`;
  }

  /**
   * Extract table names from SQL
   */
  private extractTableNames(sql: string): string[] {
    const tableRegex = /CREATE TABLE(?:\s+IF NOT EXISTS)?\s+["`]?(\w+)["`]?/gi;
    const tables: string[] = [];
    let match;

    while ((match = tableRegex.exec(sql)) !== null) {
      tables.push(match[1]);
    }

    return tables;
  }

  /**
   * Generate down migration (drop tables)
   */
  private generateDownMigration(tableNames: string[]): string {
    if (tableNames.length === 0) {
      return `// TODO: Add rollback logic`;
    }

    const drops = tableNames
      .reverse()
      .map((table) => `await db.run('DROP TABLE IF EXISTS ${table}');`)
      .join('\n    ');

    return drops;
  }
}
