/**
 * Custom worker entry point for Cloudflare
 * This file exports Durable Object classes alongside the Next.js app
 */

// Re-export the OpenNext worker handler generated by `opennextjs-cloudflare build`.
// Wrangler will bundle this file (and its deps) as the actual deployed worker.
export * from './.open-next/index.js';
export { default } from './.open-next/index.js';

// Durable Objects temporarily disabled - uncomment when needed
// Export RealtimeActor Durable Object for Cloudflare bindings.
//
// NOTE: We intentionally export a concrete class from this entry module.
// Some workerd/wrangler combinations fail to detect DO classes through
// bare re-exports, which produces:
//   "... referenced the class 'RealtimeActor', but no such Durable Object class is exported ..."
//
// We still keep OpenNext's worker handler separate (above) so we don't force
// OpenNext to bundle `@cloudflare/actors` during its own build step.
// import { RealtimeActor as BaseRealtimeActor } from "@ottabase/cf-realtime/server";
// export class RealtimeActor extends BaseRealtimeActor {}
