packages:
  - apps/*
  - packages/*

catalog:
  "@babel/core": ^7.28.5
  "@babel/preset-env": ^7.28.5
  "@babel/preset-react": ^7.28.5
  "@babel/preset-typescript": ^7.28.5
  "@prisma/adapter-d1": ^5.22.0
  "@prisma/client": ^5.22.0
  "@radix-ui/react-slot": ^1.1.1
  "@radix-ui/react-switch": ^1.1.1
  "@radix-ui/react-tabs": ^1.1.1
  "@radix-ui/react-tooltip": ^1.1.7
  "@storybook/addon-docs": ^9.1.16
  "@storybook/addon-links": ^9.1.16
  "@storybook/addon-styling-webpack": ^2.0.0
  "@storybook/react-webpack5": ^9.1.16
  "@storybook/test": ^9.1.15
  "@tabler/icons-react": ^3.35.0
  "@tailwindcss/forms": ^0.5.10
  "@tailwindcss/typography": ^0.5.18
  "@types/node": ^20.19.17
  "@types/react": ^18.3.24
  "@types/react-dom": ^18.3.7
  "@typescript-eslint/eslint-plugin": ^8.46.2
  "@typescript-eslint/parser": ^8.46.2
  autoprefixer: ^10.4.21
  babel-loader: ^9.2.1
  class-variance-authority: ^0.7.0
  clsx: ^2.1.0
  critters: ^0.0.22
  css-loader: ^7.1.2
  eslint: ^9.36.0
  eslint-config-next: ^15.5.3
  eslint-plugin-storybook: ^0.11.6
  jotai: ^2.14.0
  lucide-react: ^0.468.0
  next: ^15.5.3
  next-themes: ^0.4.6
  postcss: ^8.5.6
  postcss-loader: ^7.3.4
  postcss-preset-env: ^9.6.0
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  prettier: ^3.0.0
  prisma: ^5.22.0
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  sonner: ^1.5.1
  storybook: ^9.1.16
  style-loader: ^4.0.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  tsup: ^8.5.0
  tsx: ^4.19.2
  typescript: ^5.9.2
