// ====================================================================
// otta-web — the AI composition root (@ottabase/ottaai)
// --------------------------------------------------------------------
// THE GOLDEN PATH, in one file. A consuming app should need this plus one
// route-mount line plus one settings component — not the ~1,700 lines a
// hand-rolled equivalent costs.
//
// WHAT THE APP OWNS (and this file therefore supplies):
//   • authentication and sessions
//   • the security-context mapper and the membership verifier
//   • wiring RBAC into `authorize`
//   • `defer` (ctx.waitUntil)
//   • the task declarations, their gate strengths, and their prompts
//   • quota storage and enforcement policy
//
// WHAT THE PACKAGE OWNS: envelope format, keyring, re-wrap; schema, model,
// policy factory, field metadata; the provider registry; verdicts, scoring,
// merge; the resolution decision; transport + instrumented client; verify-a-key
// and its rate limiter; the shared error taxonomy; the status primitive.
// ====================================================================

import { trackCoreEvent } from '@ottabase/analytics';
import { getSession } from '@ottabase/auth/backend';
import { createKeyring, type AiTaskPolicy, type AiTenancyTuple, type Keyring } from '@ottabase/ottaai';
import { createKvVerifyLimiter, type AiEventMap, type AiEventName, type EventSink } from '@ottabase/ottaai/resolver';
import {
    createAiProvisioningWithStorage,
    createRbacAuthorize,
    type AiProvisioningWithStorage,
} from '@ottabase/ottaai/ottaorm';
import { createGatewayTransport } from '@ottabase/ottaai/transports/gateway';
import { OrganizationMember } from '@ottabase/ottaorm/models';
import type { SecurityContext } from '@ottabase/ottaorm';
import { getOttabaseConfig } from '../../ottabase/config.loader';
// NO IMPORT FOR `CloudflareEnv` — it is AMBIENT.
//
// `cloudflare-env.d.ts` is generated by `pnpm cf-typegen` and declares
// `interface CloudflareEnv extends Cloudflare.Env {}` with NO top-level export, i.e. a
// global. `import type { CloudflareEnv } from '…/cloudflare-env'` therefore fails with
// TS2306 "not a module" — which is why ~25 files across this app currently do not
// type-check. The correct usage is to reference the global directly, as here.
import { createAiRateLimiter, platformSpendWarning } from './ai-rate-limit';
import { getAuthOptions, getSecurityContext } from './auth-utils';
import { ensureDbConnection } from './db-utils';

// ---------------------------------------------------------------------------
// Task declarations — the ONLY thing call sites name
// ---------------------------------------------------------------------------

/**
 * A task's GATE STRENGTH is the entire commercial argument of BYOK, and it is a property
 * of the TASK rather than of the plan: a free user WITH a key gets the premium path, and a
 * paying user WITHOUT one does not.
 *
 *  • `soft`     — cheap work where the platform floor is good enough; BYOK is the upsell.
 *  • `required` — the tenant's own key, or the feature is blocked. Use where the free
 *                 floor is not accurate enough to ship under the brand and premium
 *                 inference for every free user is not funded.
 */
export const AI_TASKS = {
    /** General assistant text. Runs free on the platform model. */
    assist: 'assist',
    /** Summarise a blog post or a long document. */
    summarize: 'summarize',
    /** Long-document extraction — expensive, tenant-key only. */
    extract: 'extract',
    /** Vectorise text for semantic search, similarity and recommendations. */
    embed: 'embed',
} as const;

export type AiTaskKey = (typeof AI_TASKS)[keyof typeof AI_TASKS];

const TASK_POLICIES: AiTaskPolicy[] = [
    {
        key: AI_TASKS.assist,
        label: 'Assistant',
        gate: 'soft',
    },
    {
        key: AI_TASKS.summarize,
        label: 'Summarise',
        gate: 'soft',
        // Cheap text work. The tenant is paying when they bring a key, so their model wins.
        modelPolicy: 'tenant-preferred',
    },
    {
        key: AI_TASKS.extract,
        label: 'Document extraction',
        // NARROWING ONLY. app `auto` ∧ task `byok` ⇒ `byok`: the gate lives in the
        // RESOLVER, not the browser.
        mode: 'byok',
        gate: 'required',
        // NO `requiredCapabilities: ['vision']` — DELIBERATE, do not "restore" it.
        //
        // @ottabase/ottaai's call contract is TEXT CHAT: `AiCallOptions` message content is
        // a plain string, so there is no way to actually send an image. Requiring `vision`
        // therefore filtered out perfectly usable text credentials in exchange for a
        // capability this route cannot exercise — a stricter gate that buys nothing and
        // blocks tenants whose key would have worked.
        //
        // If multimodal content types are ever added to `AiCallOptions`, add the requirement
        // back in the SAME change.
    },
    {
        key: AI_TASKS.embed,
        label: 'Embeddings',
        // The shipped AI Gateway embedding wire is deliberately OpenAI-only. Pinning the
        // model does two useful things at once: an OpenAI tenant key can serve embeddings
        // even when its chat default is GPT, and a non-OpenAI credential is filtered out
        // before a call carrying that credential reaches a provider-specific endpoint.
        modelPolicy: 'task-pinned',
        pinnedModels: { openai: 'text-embedding-3-small' },
        // This is also the platform-path model. A deployment using a non-OpenAI platform
        // provider remains configured for chat, but the transport refuses embedding calls
        // explicitly rather than guessing at another provider's wire format.
        defaultModel: 'openai/text-embedding-3-small',
        requiredCapabilities: ['embedding'],
    },
];

// ---------------------------------------------------------------------------
// Keyring
// ---------------------------------------------------------------------------

/**
 * Build the keyring from env.
 *
 * `AI_CREDENTIAL_KEYRING` is a JSON map `{"<keyId>": "<base64 secret>"}` and
 * `AI_CREDENTIAL_KEY_ID` names the write key — that pair is what makes ROTATION possible
 * (single → dual → drain → retire). `AI_CREDENTIAL_SECRET` is the single-key convenience
 * for a first deploy and is equivalent to `{"k1": "<secret>"}` with `currentKeyId: 'k1'`.
 *
 * Generate with a CSPRNG, never type one:  `openssl rand -base64 48`
 */
export function buildAiKeyring(env: CloudflareEnv): Keyring | null {
    const raw = (env as unknown as Record<string, string | undefined>).AI_CREDENTIAL_KEYRING;
    if (raw) {
        let keys: Record<string, string>;
        try {
            keys = JSON.parse(raw) as Record<string, string>;
        } catch {
            throw new Error('AI_CREDENTIAL_KEYRING is not valid JSON. Expected {"<keyId>": "<base64 secret>"}.');
        }
        const currentKeyId =
            (env as unknown as Record<string, string | undefined>).AI_CREDENTIAL_KEY_ID ?? Object.keys(keys)[0];
        if (!currentKeyId) throw new Error('AI_CREDENTIAL_KEYRING is empty.');
        return createKeyring({ keys, currentKeyId });
    }

    const single = (env as unknown as Record<string, string | undefined>).AI_CREDENTIAL_SECRET;
    if (!single) return null;
    return createKeyring({ keys: { k1: single }, currentKeyId: 'k1' });
}

// ---------------------------------------------------------------------------
// Platform config
// ---------------------------------------------------------------------------

/** `CFAI_<PROVIDER>_API_KEY`, matching the existing Cloudflare-AI demo env convention. */
function platformProviderKey(env: CloudflareEnv, provider: string | null): string | undefined {
    if (!provider) return undefined;
    const key = `CFAI_${provider.toUpperCase().replace(/-/g, '_')}_API_KEY`;
    return (env as unknown as Record<string, string | undefined>)[key];
}

/**
 * The OPERATOR-ONLY transport bag: values that decide WHERE a request goes.
 *
 * FROM ENV, NOT FROM `features.ottaai`. `config.loader` exports the whole `features.ottaai`
 * object to the CLIENT as `OTTAAI_CONFIG`, and this bag can legitimately carry request
 * headers — so putting it in the config file would ship an operator header set to every
 * browser. Env keeps it server-side, alongside `CFAI_GATEWAY_TOKEN` and the provider keys.
 *
 * Today only Azure OpenAI needs it: its gateway path is
 * `/azure-openai/{resource}/{deployment}/chat/completions?api-version=…`, and WITHOUT these
 * three values the transport reports Azure as unservable — the settings form then stops
 * offering it, instead of accepting a real tenant key for calls that can never route.
 *
 * Extending: add the provider's operator-only keys here and to `.env.example`. Anything a
 * TENANT may set belongs on the credential's own `transportConfig`, which the merge filters
 * against the registry's `destinationKeys`.
 */
function platformTransportConfig(env: CloudflareEnv): Record<string, unknown> | undefined {
    const read = (key: string) => (env as unknown as Record<string, string | undefined>)[key]?.trim() || undefined;

    const bag: Record<string, unknown> = {};
    const resourceName = read('CFAI_AZURE_RESOURCE_NAME');
    const deploymentName = read('CFAI_AZURE_DEPLOYMENT_NAME');
    const apiVersion = read('CFAI_AZURE_API_VERSION');
    // ALL THREE OR NONE — a partial Azure config builds no URL, so treating it as configured
    // would put Azure back in the form and reproduce exactly the bug this closes.
    if (resourceName && deploymentName && apiVersion) {
        Object.assign(bag, { resourceName, deploymentName, apiVersion });
    }

    return Object.keys(bag).length > 0 ? bag : undefined;
}

// ---------------------------------------------------------------------------
// The instance
// ---------------------------------------------------------------------------

export interface AiRequestContext {
    request: Request;
    env: CloudflareEnv;
    /** Supply `ctx.waitUntil` from the worker, or health + attribution writes are lost. */
    waitUntil?: (promise: Promise<unknown>) => void;
}

/**
 * The host-context marker the route factory passes back into `contextFrom`.
 *
 * The instance is built PER REQUEST and already closes over this request's authenticated
 * security context, so the marker carries no data — it exists only so the route factory
 * can say "authenticated" (a value) or "not" (null), and so nothing else in the app can
 * mint a resolution context by hand.
 */
export interface AiHostAuth {
    readonly authenticated: true;
}

export type AiInstance = AiProvisioningWithStorage<AiHostAuth>;

let bootLogged = false;

/**
 * Build the per-request provisioning instance.
 *
 * PER REQUEST, ON PURPOSE. The `authorize` hook closes over THIS request's
 * already-authenticated `SecurityContext`, so role and membership are RE-CHECKED on every
 * request rather than trusted from a session minted before the user was demoted.
 *
 * Returns null when AI is not configured — the feature is DORMANT BY DEFAULT, so a
 * deployment with no keys at all boots, serves, and simply does not show the affordances.
 */
export async function getAiProvisioning(
    context: AiRequestContext,
): Promise<{ ai: AiInstance; security: SecurityContext } | null> {
    const { request, env } = context;
    // `getOttabaseConfig` takes `EnvLike = Record<string, unknown>`, and a concrete INTERFACE
    // does not satisfy an index signature in TypeScript (a type alias would). The cast is the
    // documented way across this app's env reads — see the `CLOUDFLARE_ACCOUNT_ID` lookups
    // below, which cast for the same reason.
    const config = getOttabaseConfig(env as unknown as Record<string, unknown>);
    if (!config.packages.ottaai) return null;

    const keyring = buildAiKeyring(env);
    // A missing keyring is "not configured" — but ONLY because no credential row can exist
    // without it. Once rows exist, the resolver reports CREDENTIAL_UNREADABLE rather than
    // "not configured", so a user is never sent to re-enter a key that is already there.
    if (!keyring) return null;

    ensureDbConnection(env);

    const session = await getSession(request, env as never, getAuthOptions(env));
    const security: SecurityContext = await getSecurityContext(request, session, env);

    const feature = config.features.ottaai;
    const accountId = (env as unknown as Record<string, string | undefined>).CLOUDFLARE_ACCOUNT_ID;
    const gateway = feature.gateway ?? (env as unknown as Record<string, string | undefined>).CFAI_GATEWAY_NAME;
    const platformProvider = feature.platformProvider;
    const platformKey = platformProviderKey(env, platformProvider);

    const rbacAuthorize = createRbacAuthorize(security);

    const ai = createAiProvisioningWithStorage<AiHostAuth>({
        keyring,
        transport: createGatewayTransport(),
        platform: {
            accountId,
            gateway: gateway ?? undefined,
            gatewayToken: (env as unknown as Record<string, string | undefined>).CFAI_GATEWAY_TOKEN,
            provider: platformProvider ?? undefined,
            providerKey: platformKey,
            model: feature.platformModel ?? undefined,
            // Operator-only destination values. The transport reads this to decide which
            // providers this deployment can actually route to — see `platformTransportConfig`.
            transportConfig: platformTransportConfig(env),
        },
        tasks: TASK_POLICIES,

        mode: feature.mode,
        strategy: feature.strategy,
        appScope: feature.appScope,
        byokEnabled: feature.byokEnabled,
        // THE SERVER MUST SEE THIS DIAL. It also reaches `AiProvidersPage` as the settings
        // component's `allowOrgScope` prop — but a prop only hides a radio button, and
        // `POST /api/ai/credentials {"scope":"organization"}` from curl does not go through
        // React. Passing it here is what makes the route factory refuse the write.
        allowOrgCredentials: feature.allowOrgCredentials,

        /**
         * The tenancy mapper — THE ONLY function that mints the branded context.
         *
         * `appId` comes from CONFIG, never from the `x-app-id` header: it is an isolation
         * boundary, and a boundary derived from client-supplied input is not one.
         * (`getSecurityContext` honours the header for RLS scope selection; the CALL plane
         * deliberately does not.)
         *
         * `organizationId` is already membership-verified by `getSecurityContext`, which
         * nulls an active org the user is not an active member of.
         *
         * `impersonated` is FALSE because this repo has no support-staff impersonation —
         * verified, not assumed. If one is ever added, the flag must be derived HERE from
         * the session, never accepted as a call-site parameter.
         */
        contextFrom: (): AiTenancyTuple => ({
            userId: security.userId ?? null,
            organizationId: security.organizationId ?? null,
            appId: config.appId,
            impersonated: false,
        }),

        /** Unconditional, server-side membership verification. */
        verifyMembership: async ({ userId, organizationId }) => {
            if (!userId) return false;
            if (security.platformAdmin === true) return true;
            if (Array.isArray(security.memberOrganizationIds)) {
                return security.memberOrganizationIds.includes(organizationId);
            }
            return OrganizationMember.isMember(userId, organizationId);
        },

        /** RBAC inside the authorize hook — the framework's native shape. */
        authorize: ({ credential }) => rbacAuthorize({ credential }),

        /**
         * INFERENCE RATE LIMITING — the only thing standing between an authenticated user and
         * the operator's provider budget.
         *
         * Wired as the package's `quota` hook rather than as route middleware because the hook
         * receives `source`: platform-paid inference fails CLOSED when the limiter is
         * unavailable, BYOK fails open. A pre-resolution check cannot make that distinction.
         * See `ai-rate-limit.ts` for the full reasoning and the stated tolerance.
         *
         * NOT a billing quota. It bounds burst, not total spend.
         */
        quota: createAiRateLimiter({
            store: env.OBCF_KV ?? null,
            appId: config.appId,
            limits: feature.rateLimit,
        }),

        /**
         * Health writes, attribution and tier-two audit all go through here. Without a real
         * `waitUntil` the runtime cancels them at response — SILENT DATA LOSS.
         */
        defer: context.waitUntil ?? ((promise) => void Promise.resolve(promise).catch(() => {})),

        eventSink: createAnalyticsEventSink(env, config.appId),

        handlers: {
            // Named `contextFromRequest` and owned by the APP — deliberately a different
            // name from the instance's `contextFrom`, because two functions called
            // `contextFrom` is a conflation waiting to happen.
            contextFromRequest: () => (security.userId ? ({ authenticated: true } as const) : null),
            /**
             * A DURABLE verification budget.
             *
             * The package's in-memory fallback is module-scoped, which survives a request
             * but not isolate churn — and an attacker rotating connections gets a fresh
             * budget on each new isolate. Backing it with KV is what actually stops the
             * Test button being a credential-stuffing oracle running from our IP range and
             * through our gateway account.
             */
            verifyLimiter: env.OBCF_KV ? createKvVerifyLimiter(env.OBCF_KV) : undefined,
        },

        onBoot: (summary) => {
            // Log the effective dials ONCE per isolate, so "which strategy is live?" is
            // always in the record rather than re-derived from three config files.
            if (bootLogged) return;
            bootLogged = true;

            // "Paid inference is enabled but unprotected" is SILENT BY NATURE — everything
            // works and the bill arrives later — so it goes in the summary AND as a warning.
            //
            // `platformRouteUsable` COMES FROM THE PACKAGE, which asks the transport whether a
            // platform call can actually be made. Deriving it here from "is CFAI_<X>_API_KEY
            // set?" missed gateway-billed inference — no provider key, still the operator's
            // money — so the one deployment shape that most needed this warning never got it.
            const routeUsable = summary.platformRouteUsable === true;
            const unprotected = platformSpendWarning(env, routeUsable, feature.rateLimit);
            console.log('[ottaai] effective configuration', {
                ...summary,
                rateLimit: feature.rateLimit,
                ...(unprotected ? { platformSpendUnprotected: unprotected } : {}),
            });
            if (unprotected) console.warn(`[ottaai] ${unprotected}`);
        },
    });

    // The route layer needs BOTH: the instance to act with, and the security context to
    // gate on. The inference route must refuse an anonymous caller — the credential routes
    // get that from the package's route factory, the inference route does not.
    return { ai, security };
}

/**
 * Route package events into the analytics dataset the app already owns.
 *
 * The sink is an INTERFACE WITH AN ANALYTICS ADAPTER, not a new subsystem — and the
 * payloads are allow-listed by their types, so a secret cannot reach the aggregator.
 */
function createAnalyticsEventSink(env: CloudflareEnv, appId: string): EventSink {
    return (<K extends AiEventName>(event: K, payload: AiEventMap[K]) => {
        const dataset = env.OBCF_ANALYTICS_CORE;
        if (!dataset) return;
        const fields = payload as unknown as Record<string, unknown>;
        trackCoreEvent({
            dataset,
            event: `ottaai.${event}`,
            appId,
            userId: typeof fields.userId === 'string' ? fields.userId : undefined,
            metadata: [
                String(fields.taskKey ?? ''),
                String(fields.source ?? ''),
                String(fields.reason ?? fields.verdict ?? fields.errorCode ?? ''),
                String(fields.provider ?? ''),
                String(fields.organizationId ?? ''),
            ],
            value: typeof fields.latencyMs === 'number' ? fields.latencyMs : 1,
        });
    }) as EventSink;
}
