/**
 * Custom worker entry point for Cloudflare
 * Integrates brand-engine with Next.js OpenNext deployment
 */

import { registerBuiltInThemes } from '@ottabase/brand-engine';

// Register built-in themes so they're available throughout the app
// Available themes: default, neo, crisp, funky, artisan, midnight, rose, verdant
registerBuiltInThemes();

// Re-export the OpenNext worker handler generated by `opennextjs-cloudflare build`.
// Wrangler will bundle this file (and its deps) as the actual deployed worker.
export * from './.open-next/index.js';
export { default } from './.open-next/index.js';
