export {
    buildHomepagePublicPayloadV1,
    type BuildHomepagePublicPayloadV1Options,
    type HomepageDbActionInput,
    type HomepageDbDisplayInput,
    type HomepageDbFeatureInput,
    type HomepageDbSectionInput,
} from './build-payload';
export { parseHomepagePublicPayloadV1, safeParseHomepagePublicPayloadV1 } from './parse';
export {
    getHomepageVariantIdsForSlot,
    homepageSlotVariantRegistry,
    type HomepageSlotRegistryEntry,
    type HomepageVariantMeta,
} from './slot-registry';
export {
    homepageAboutContentSchema,
    homepageActionSchema,
    homepageExposedPageSchema,
    homepageCtaContentSchema,
    homepageFeatureItemSchema,
    homepageFeaturesContentSchema,
    homepageFooterContentJsonSchema,
    homepageHeroContentSchema,
    homepageNavbarContentJsonSchema,
    homepageNavLinkSchema,
    homepagePublicPayloadSlotsSchema,
    homepagePublicPayloadV1Schema,
    homepageSlotNames,
    homepageVariantBySlotSchema,
    type HomepageAboutContent,
    type HomepageAction,
    type HomepageCtaContent,
    type HomepageExposedPage,
    type HomepageFeatureItem,
    type HomepageFeaturesContent,
    type HomepageFooterContent,
    type HomepageHeroContent,
    type HomepageNavbarContent,
    type HomepageNavLink,
    type HomepagePublicPayloadV1,
    type HomepageSlotName,
} from './schemas';
