#!/usr/bin/env node

import { writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import pc from "picocolors";
import { config as loadDotenv } from "dotenv";
import { expand as expandDotenv } from "dotenv-expand";
import { extractMetadata } from "./core.js";
import type { EnvVarMetadata } from "./types.js";

// Load environment variables
const dotenvOutput = loadDotenv();
expandDotenv(dotenvOutput);

const COMMANDS = {
  generate: "generate",
  validate: "validate",
  list: "list",
  check: "check",
  help: "help",
} as const;

type Command = (typeof COMMANDS)[keyof typeof COMMANDS];

function printHelp() {
  console.log(`
${pc.bold(pc.cyan("Ottabase Environment Variables CLI"))}

${pc.bold("Usage:")}
  ottabase-env <command> [options]

${pc.bold("Commands:")}
  ${pc.green("generate")}  Generate .env.example from schemas
  ${pc.green("validate")}  Validate current environment variables
  ${pc.green("list")}      List all environment variables and their metadata
  ${pc.green("check")}     Check for missing required variables
  ${pc.green("help")}      Show this help message

${pc.bold("Options:")}
  --schema <path>   Path to schema file (default: auto-discover)
  --output <path>   Output path for .env.example (default: .env.example)
  --package <name>  Filter by package name

${pc.bold("Examples:")}
  ${pc.dim("# Generate .env.example from all schemas")}
  ottabase-env generate

  ${pc.dim("# Validate current environment")}
  ottabase-env validate

  ${pc.dim("# List all required variables")}
  ottabase-env list

  ${pc.dim("# Check for missing variables")}
  ottabase-env check
`);
}

function parseArgs(args: string[]): {
  command: Command;
  options: Record<string, string>;
} {
  const command = (args[0] || "help") as Command;
  const options: Record<string, string> = {};

  for (let i = 1; i < args.length; i++) {
    if (args[i].startsWith("--")) {
      const key = args[i].slice(2);
      const value = args[i + 1];
      if (value && !value.startsWith("--")) {
        options[key] = value;
        i++;
      }
    }
  }

  return { command, options };
}

async function loadSchemas(): Promise<{
  name: string;
  metadata: EnvVarMetadata[];
}[]> {
  const schemasPath = resolve(__dirname, "./schemas/index.js");

  if (!existsSync(schemasPath)) {
    console.error(pc.red("❌ Schemas not found. Make sure to build the package first."));
    process.exit(1);
  }

  try {
    const schemas = await import(schemasPath);

    return [
      {
        name: "@ottabase/cf",
        metadata: extractMetadata(schemas.cfEnvSchema),
      },
      {
        name: "@ottabase/db",
        metadata: extractMetadata(schemas.dbEnvSchema),
      },
      {
        name: "@ottabase/config",
        metadata: extractMetadata(schemas.configEnvSchema),
      },
    ];
  } catch (error) {
    console.error(pc.red("❌ Failed to load schemas:"), error);
    process.exit(1);
  }
}

function generateEnvExample(
  schemas: { name: string; metadata: EnvVarMetadata[] }[],
  outputPath: string,
) {
  let content = "# Ottabase Environment Variables\n";
  content += "# Generated by @ottabase/env\n";
  content += `# Generated at: ${new Date().toISOString()}\n\n`;

  for (const schema of schemas) {
    content += `#\n# ${schema.name}\n#\n\n`;

    for (const meta of schema.metadata) {
      // Add description as comment
      if (meta.description) {
        content += `# ${meta.description}\n`;
      }

      // Add type info
      let typeInfo = `# Type: ${meta.type}`;
      if (meta.enumValues) {
        typeInfo += ` (${meta.enumValues.join(" | ")})`;
      }
      if (!meta.required) {
        typeInfo += " (optional)";
      }
      content += `${typeInfo}\n`;

      // Add default value if present
      if (meta.defaultValue !== undefined) {
        content += `# Default: ${meta.defaultValue}\n`;
      }

      // Add example or placeholder
      const placeholder = meta.example || getPlaceholder(meta);
      if (meta.required) {
        content += `${meta.name}=${placeholder}\n`;
      } else {
        content += `# ${meta.name}=${placeholder}\n`;
      }

      content += "\n";
    }
  }

  writeFileSync(outputPath, content, "utf-8");
  console.log(pc.green(`✓ Generated ${outputPath}`));
}

function getPlaceholder(meta: EnvVarMetadata): string {
  switch (meta.type) {
    case "url":
      return "https://example.com";
    case "email":
      return "user@example.com";
    case "number":
      return meta.name.includes("PORT") ? "3000" : "0";
    case "boolean":
      return "false";
    case "enum":
      return meta.enumValues?.[0] || "";
    case "json":
      return "{}";
    default:
      if (meta.name.includes("TOKEN") || meta.name.includes("KEY")) {
        return "your-secret-token-here";
      }
      if (meta.name.includes("URL")) {
        return "https://example.com";
      }
      if (meta.name.includes("ID")) {
        return "your-id-here";
      }
      return "value";
  }
}

function listVariables(
  schemas: { name: string; metadata: EnvVarMetadata[] }[],
  packageFilter?: string,
) {
  console.log(pc.bold("\n📋 Environment Variables\n"));

  for (const schema of schemas) {
    if (packageFilter && schema.name !== packageFilter) {
      continue;
    }

    console.log(pc.cyan(pc.bold(`\n${schema.name}`)));
    console.log(pc.dim("─".repeat(50)));

    const required = schema.metadata.filter((m) => m.required);
    const optional = schema.metadata.filter((m) => !m.required);

    if (required.length > 0) {
      console.log(pc.yellow("\nRequired:"));
      for (const meta of required) {
        console.log(`  ${pc.green("●")} ${pc.bold(meta.name)} (${meta.type})`);
        if (meta.description) {
          console.log(`    ${pc.dim(meta.description)}`);
        }
      }
    }

    if (optional.length > 0) {
      console.log(pc.blue("\nOptional:"));
      for (const meta of optional) {
        let line = `  ${pc.blue("○")} ${meta.name} (${meta.type})`;
        if (meta.defaultValue) {
          line += pc.dim(` = ${meta.defaultValue}`);
        }
        console.log(line);
        if (meta.description) {
          console.log(`    ${pc.dim(meta.description)}`);
        }
      }
    }
  }

  console.log();
}

function checkMissing(schemas: { name: string; metadata: EnvVarMetadata[] }[]) {
  console.log(pc.bold("\n🔍 Checking for missing variables...\n"));

  let hasErrors = false;
  let totalRequired = 0;
  let totalMissing = 0;

  for (const schema of schemas) {
    const required = schema.metadata.filter((m) => m.required);
    totalRequired += required.length;

    const missing = required.filter((m) => !process.env[m.name]);

    if (missing.length > 0) {
      hasErrors = true;
      totalMissing += missing.length;

      console.log(pc.red(`\n❌ ${schema.name}`));
      console.log(pc.dim("─".repeat(50)));

      for (const meta of missing) {
        console.log(`  ${pc.red("✗")} ${pc.bold(meta.name)}`);
        if (meta.description) {
          console.log(`    ${pc.dim(meta.description)}`);
        }
        console.log(`    ${pc.yellow("Add this to your .env file")}`);
      }
    } else if (required.length > 0) {
      console.log(pc.green(`✓ ${schema.name} - all required variables present`));
    }
  }

  console.log();

  if (hasErrors) {
    console.log(
      pc.red(`\n❌ ${totalMissing} of ${totalRequired} required variables are missing\n`),
    );
    console.log(pc.yellow("💡 Run 'ottabase-env generate' to create .env.example\n"));
    process.exit(1);
  } else {
    console.log(pc.green(`✓ All ${totalRequired} required variables are present\n`));
  }
}

async function validateEnvironment() {
  console.log(pc.bold("\n🔍 Validating environment...\n"));

  const schemasModule = await import(resolve(__dirname, "./schemas/index.js"));

  const validations = [
    { name: "@ottabase/cf", schema: schemasModule.cfEnvSchema },
    { name: "@ottabase/db", schema: schemasModule.dbEnvSchema },
    { name: "@ottabase/config", schema: schemasModule.configEnvSchema },
  ];

  let hasErrors = false;

  for (const { name, schema } of validations) {
    try {
      schema.parse(process.env);
      console.log(pc.green(`✓ ${name}`));
    } catch (error: any) {
      hasErrors = true;
      console.log(pc.red(`✗ ${name}`));

      if (error.errors) {
        for (const err of error.errors) {
          const path = err.path.join(".");
          console.log(`  ${pc.yellow("→")} ${path}: ${err.message}`);
        }
      }
    }
  }

  console.log();

  if (hasErrors) {
    console.log(pc.red("❌ Validation failed\n"));
    process.exit(1);
  } else {
    console.log(pc.green("✓ All environment variables are valid\n"));
  }
}

async function main() {
  const { command, options } = parseArgs(process.argv.slice(2));

  switch (command) {
    case COMMANDS.help: {
      printHelp();
      break;
    }

    case COMMANDS.generate: {
      const schemas = await loadSchemas();
      const outputPath = options.output || ".env.example";
      generateEnvExample(schemas, outputPath);
      break;
    }

    case COMMANDS.list: {
      const schemas = await loadSchemas();
      listVariables(schemas, options.package);
      break;
    }

    case COMMANDS.check: {
      const schemas = await loadSchemas();
      checkMissing(schemas);
      break;
    }

    case COMMANDS.validate: {
      await validateEnvironment();
      break;
    }

    default: {
      console.error(pc.red(`Unknown command: ${command}`));
      printHelp();
      process.exit(1);
    }
  }
}

main().catch((error) => {
  console.error(pc.red("Fatal error:"), error);
  process.exit(1);
});
